[package]
name = "machine_learning"
version = "0.1.0"
edition = "2024"

[dependencies]
comms = { path = "../comms" }
futures = "0.3.32"
ndarray = { version = "0.17.2", features = ["rayon"] }
ndarray-rand = "0.16.0"
rand = "0.9.2"
tokio = { version = "1.49.0", features = ["full"] }
