[package]
name = "orchestrator"
version = "0.1.0"
edition = "2024"

[dependencies]
comms = { path = "../comms" }
tokio = { version = "1", features = ["rt-multi-thread", "macros", "net"] }
log = "0.4"
env_logger = "0.11"