[package]
name = "parameter_server"
version = "0.1.0"
edition = "2024"

[dependencies]
comms = { version = "0.1.0", path = "../comms" }
parking_lot = "0.12.5"
rayon = "1.11.0"
tokio = { version = "1.48.0", features = ["full"] }
trait-variant = "0.1.2"
