[package]
name = "server"
version = "0.1.0"
edition = "2024"

[dependencies]
atomic_float = "1.1.0"
comms = { version = "0.1.0", path = "../comms" }
rayon = "1.11.0"
tokio = { version = "1.48.0", features = ["full"] }
