[package]
name = "worker"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1", features = ["rt-multi-thread", "macros", "net", "signal"] }
log = { version = "0.4.29", features = ["kv"] }
env_logger = "0.11"

comms = { path = "../comms" }
machine_learning = { path = "../machine_learning" }

[dev-dependencies]
tokio = { version = "1", features = ["rt-multi-thread", "macros", "time", "io-util"] }
